language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit